# Generated by Django 4.1.2 on 2022-10-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposter', '0002_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='url',
            field=models.CharField(max_length=100, unique=True, verbose_name='Адрес группы'),
        ),
    ]
