# Generated by Django 4.1.2 on 2022-11-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('reposter', '0003_group_active_alter_group_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabHours',
            fields=[
                ('crontabschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.crontabschedule')),
            ],
            bases=('django_celery_beat.crontabschedule',),
        ),
    ]
